// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/search-trips.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/data/mockTrips.ts
var companies = {
  "himalayan-trails": {
    id: "himalayan-trails",
    name: "Himalayan Trails Co.",
    logo: "\u{1F3D4}\uFE0F",
    verified: true,
    about: "Specialists in Himalayan adventures since 2016. 1,200+ travelers hosted across Manali, Spiti & Ladakh.",
    rating: 4.8,
    trips: 24
  },
  "coastal-escapes": {
    id: "coastal-escapes",
    name: "Coastal Escapes",
    logo: "\u{1F334}",
    verified: true,
    about: "Beach and coastal experiences across Goa, Andaman, and Kerala. Curated by locals, loved by travelers.",
    rating: 4.7,
    trips: 18
  },
  "kerala-trails": {
    id: "kerala-trails",
    name: "Kerala Trails",
    logo: "\u{1F6F6}",
    verified: true,
    about: "Backwater & hill-country journeys, hand-built by Kerala natives.",
    rating: 4.9,
    trips: 12
  },
  "royal-rajasthan": {
    id: "royal-rajasthan",
    name: "Royal Rajasthan Tours",
    logo: "\u{1F3F0}",
    verified: true,
    about: "Heritage and palace experiences across Rajasthan with vetted local guides.",
    rating: 4.7,
    trips: 15
  },
  "ride-india": {
    id: "ride-india",
    name: "Ride India Expeditions",
    logo: "\u{1F3CD}\uFE0F",
    verified: true,
    about: "Motorcycle expeditions across Ladakh, Spiti & the North-East. Safety-first, story-rich.",
    rating: 4.9,
    trips: 9
  }
};
var VID = {
  // Mountains / Himalayas — drone over snowy peaks
  mountains: "https://videos.pexels.com/video-files/31476513/13421170_3840_2160_60fps.mp4",
  // Tropical beach — palms + turquoise water
  beach: "https://videos.pexels.com/video-files/34590035/14659202_1920_1080_30fps.mp4",
  // Kerala-style backwaters / tropical river
  backwaters: "https://videos.pexels.com/video-files/34742689/14728150_3840_2160_30fps.mp4",
  // Desert dunes — sand & dunes
  desert: "https://videos.pexels.com/video-files/33911366/14391353_3840_2160_24fps.mp4",
  // Island aerial — sea & coastline
  islands: "https://videos.pexels.com/video-files/20235510/20235510-uhd_3840_2160_30fps.mp4",
  // Mountain road — winding scenic road (good stand-in for Ladakh ride)
  bike: "https://videos.pexels.com/video-files/32659156/13924425_1920_1080_30fps.mp4"
};
var mockTrips = [
  {
    id: "1",
    title: "Magical Manali & Solang Valley",
    price: 12999,
    duration: "4N / 5D",
    dates: "Apr 15 \u2013 Apr 19, 2026",
    itinerary: [
      "Arrive in Manali, check-in, explore Mall Road & local cafes.",
      "Visit Solang Valley \u2013 paragliding, zorbing, and snow activities.",
      "Trek to Jogini Waterfall, visit Vashisht Temple & hot springs.",
      "Day trip to Rohtang Pass (subject to permits), scenic views.",
      "Visit Hadimba Temple, souvenir shopping, departure."
    ],
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&q=80",
    videoUrl: VID.mountains,
    plannerName: "Arjun Mehta",
    plannerAbout: "Adventure travel specialist with 8+ years of curating Himalayan experiences.",
    companyId: "himalayan-trails",
    rating: 4.8,
    booked: 47,
    popular: true,
    location: "Manali, Himachal Pradesh",
    destination: "Himachal",
    gallery: [
      "https://images.pexels.com/photos/33369518/pexels-photo-33369518.jpeg?cs=srgb&dl=pexels-ahad-hasan-1816309676-33369518.jpg&fm=jpg&_gl=1*1jon3ye*_ga*MTUzNzUzNzM5Ny4xNzc1NDg5NzU1*_ga_8JE65Q40S6*czE3NzkxMzM4NDIkbzUkZzEkdDE3NzkxMzM4NTMkajQ5JGwwJGgw",
      "https://images.pexels.com/photos/31462170/pexels-photo-31462170.jpeg?cs=srgb&dl=pexels-eslames1-31462170.jpg&fm=jpg&_gl=1*yz7dwd*_ga*MTUzNzUzNzM5Ny4xNzc1NDg5NzU1*_ga_8JE65Q40S6*czE3NzkxMzM4NDIkbzUkZzEkdDE3NzkxMzM4NTMkajQ5JGwwJGgw",
      "https://images.pexels.com/photos/36109997/pexels-photo-36109997.jpeg?cs=srgb&dl=pexels-hasan-huseyin-turan-42224442-36109997.jpg&fm=jpg&_gl=1*1jujiuc*_ga*MTUzNzUzNzM5Ny4xNzc1NDg5NzU1*_ga_8JE65Q40S6*czE3NzkxMzM4NDIkbzUkZzEkdDE3NzkxMzM4NTMkajQ5JGwwJGgw",
      "https://images.pexels.com/photos/32109154/pexels-photo-32109154.jpeg?cs=srgb&dl=pexels-ex-route-adventures-656223369-32109154.jpg&fm=jpg&_gl=1*1jj0m3u*_ga*MTUzNzUzNzM5Ny4xNzc1NDg5NzU1*_ga_8JE65Q40S6*czE3NzkxMzM4NDIkbzUkZzEkdDE3NzkxMzM4NTMkajQ5JGwwJGgw",
      "https://images.pexels.com/photos/30921917/pexels-photo-30921917.jpeg?cs=srgb&dl=pexels-uixshubh-30921917.jpg&fm=jpg&_gl=1*1qljz2o*_ga*MTUzNzUzNzM5Ny4xNzc1NDg5NzU1*_ga_8JE65Q40S6*czE3NzkxMzM4NDIkbzUkZzEkdDE3NzkxMzQ0NjMkajE1JGwwJGgw",
      "https://images.pexels.com/photos/12197113/pexels-photo-12197113.jpeg?cs=srgb&dl=pexels-sam-clickx-24038849-12197113.jpg&fm=jpg&_gl=1*hzy8bq*_ga*MTUzNzUzNzM5Ny4xNzc1NDg5NzU1*_ga_8JE65Q40S6*czE3NzkxMzM4NDIkbzUkZzEkdDE3NzkxMzQzNjkkajMyJGwwJGgw"
    ]
  },
  {
    id: "2",
    title: "Goa Beach Bliss Getaway",
    price: 8499,
    duration: "3N / 4D",
    dates: "May 1 \u2013 May 4, 2026",
    itinerary: [
      "Arrive in Goa, check-in at beach resort, sunset at Calangute.",
      "North Goa tour \u2013 Aguada Fort, Baga Beach, Anjuna Flea Market.",
      "South Goa exploration \u2013 Palolem Beach, boat ride, seafood dinner.",
      "Water sports at Baina Beach, departure."
    ],
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1200&q=80",
    videoUrl: VID.beach,
    plannerName: "Priya Sharma",
    plannerAbout: "Beach & culture enthusiast crafting relaxing coastal experiences since 2019.",
    companyId: "coastal-escapes",
    rating: 4.6,
    booked: 32,
    popular: true,
    location: "Goa",
    destination: "Goa",
    gallery: [
      "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80",
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80",
      "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?w=800&q=80",
      "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80",
      "https://images.unsplash.com/photo-1475924156734-496f6cac6ec1?w=800&q=80"
    ]
  },
  {
    id: "3",
    title: "Serene Kerala Backwaters",
    price: 15999,
    duration: "5N / 6D",
    dates: "Jun 10 \u2013 Jun 15, 2026",
    itinerary: [
      "Arrive in Kochi, Fort Kochi walk, Chinese fishing nets.",
      "Drive to Munnar \u2013 tea plantation visit, Mattupetty Dam.",
      "Munnar sightseeing \u2013 Eravikulam Park, Top Station.",
      "Drive to Alleppey, board houseboat, backwater cruise.",
      "Kovalam Beach, lighthouse visit, Ayurvedic spa.",
      "Trivandrum city tour, departure."
    ],
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200&q=80",
    videoUrl: VID.backwaters,
    plannerName: "Deepak Nair",
    plannerAbout: "Kerala native with deep knowledge of backwater routes and hidden gems.",
    companyId: "kerala-trails",
    rating: 4.9,
    booked: 63,
    popular: true,
    location: "Kerala",
    destination: "Kerala",
    gallery: [
      "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80",
      "https://images.unsplash.com/photo-1545579133-99bb5ab189bd?w=800&q=80",
      "https://images.pexels.com/photos/20083971/pexels-photo-20083971.jpeg?cs=srgb&dl=pexels-love-hater-373675099-20083971.jpg&fm=jpg&_gl=1*1je9t3t*_ga*MTUzNzUzNzM5Ny4xNzc1NDg5NzU1*_ga_8JE65Q40S6*czE3NzkxMzM4NDIkbzUkZzEkdDE3NzkxMzQ3ODUkajE5JGwwJGgw",
      "https://images.unsplash.com/photo-1531761535209-180857e963b9?w=800&q=80",
      "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&q=80",
      "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=800&q=80"
    ]
  },
  {
    id: "4",
    title: "Rajasthan Royal Heritage Tour",
    price: 18500,
    duration: "6N / 7D",
    dates: "Oct 5 \u2013 Oct 11, 2026",
    itinerary: [
      "Arrive Jaipur \u2013 Hawa Mahal, City Palace.",
      "Amber Fort, Nahargarh Fort, local bazaar.",
      "Drive to Jodhpur \u2013 Mehrangarh Fort, blue city walk.",
      "Jodhpur to Jaisalmer \u2013 Sam Sand Dunes, camel safari.",
      "Desert camping under the stars, folk music evening.",
      "Jaisalmer Fort, Patwon ki Haveli.",
      "Return to Jaipur, departure."
    ],
    image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=1200&q=80",
    videoUrl: VID.desert,
    plannerName: "Riya Patel",
    plannerAbout: "Heritage travel expert specializing in Rajasthan's royal experiences.",
    companyId: "royal-rajasthan",
    rating: 4.7,
    booked: 28,
    popular: false,
    location: "Rajasthan",
    destination: "Rajasthan",
    gallery: [
      "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&q=80",
      "https://images.pexels.com/photos/12758953/pexels-photo-12758953.jpeg?cs=srgb&dl=pexels-absoluteabhi-12758953.jpg&fm=jpg&_gl=1*9p85vn*_ga*MTUzNzUzNzM5Ny4xNzc1NDg5NzU1*_ga_8JE65Q40S6*czE3NzkxMzM4NDIkbzUkZzEkdDE3NzkxMzQ5MDMkajU5JGwwJGgw",
      "https://images.pexels.com/photos/29295304/pexels-photo-29295304.jpeg?cs=srgb&dl=pexels-gowri-manoj-2063246685-29295304.jpg&fm=jpg&_gl=1*153izda*_ga*MTUzNzUzNzM5Ny4xNzc1NDg5NzU1*_ga_8JE65Q40S6*czE3NzkxMzM4NDIkbzUkZzEkdDE3NzkxMzQ5MDMkajU5JGwwJGgw",
      "https://images.pexels.com/photos/3304374/pexels-photo-3304374.jpeg?cs=srgb&dl=pexels-manoj-gurjar-1738771-3304374.jpg&fm=jpg&_gl=1*9p85vn*_ga*MTUzNzUzNzM5Ny4xNzc1NDg5NzU1*_ga_8JE65Q40S6*czE3NzkxMzM4NDIkbzUkZzEkdDE3NzkxMzQ5MDMkajU5JGwwJGgw",
      "https://images.pexels.com/photos/19149588/pexels-photo-19149588.jpeg?cs=srgb&dl=pexels-axp-photography-500641970-19149588.jpg&fm=jpg&_gl=1*9p85vn*_ga*MTUzNzUzNzM5Ny4xNzc1NDg5NzU1*_ga_8JE65Q40S6*czE3NzkxMzM4NDIkbzUkZzEkdDE3NzkxMzQ5MDMkajU5JGwwJGgw",
      "https://images.pexels.com/photos/21300363/pexels-photo-21300363.jpeg?cs=srgb&dl=pexels-neerja-21300363.jpg&fm=jpg&_gl=1*c5u962*_ga*MTUzNzUzNzM5Ny4xNzc1NDg5NzU1*_ga_8JE65Q40S6*czE3NzkxMzM4NDIkbzUkZzEkdDE3NzkxMzQ5MDMkajU5JGwwJGgw"
    ]
  },
  {
    id: "5",
    title: "Andaman Island Adventure",
    price: 22e3,
    duration: "5N / 6D",
    dates: "Nov 20 \u2013 Nov 25, 2026",
    itinerary: [
      "Arrive Port Blair, Cellular Jail visit, light & sound show.",
      "Ferry to Havelock Island, Radhanagar Beach sunset.",
      "Scuba diving at Elephant Beach, snorkeling.",
      "Neil Island \u2013 Laxmanpur Beach, natural rock formations.",
      "Glass-bottom boat ride, mangrove kayaking.",
      "Return to Port Blair, shopping, departure."
    ],
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&q=80",
    videoUrl: VID.islands,
    plannerName: "Priya Sharma",
    plannerAbout: "Beach & culture enthusiast crafting relaxing coastal experiences since 2019.",
    companyId: "coastal-escapes",
    rating: 4.5,
    booked: 19,
    popular: false,
    location: "Andaman Islands",
    destination: "Andaman",
    gallery: [
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80",
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
      "https://images.pexels.com/photos/36880615/pexels-photo-36880615.jpeg?cs=srgb&dl=pexels-thiha-myokyaw-76503614-36880615.jpg&fm=jpg&_gl=1*o09i9*_ga*MTUzNzUzNzM5Ny4xNzc1NDg5NzU1*_ga_8JE65Q40S6*czE3NzkxMzM4NDIkbzUkZzEkdDE3NzkxMzUxNTMkajU5JGwwJGgw",
      "https://images.pexels.com/photos/19164155/pexels-photo-19164155.jpeg?cs=srgb&dl=pexels-visualkarsa-19164155.jpg&fm=jpg&_gl=1*see2ip*_ga*MTUzNzUzNzM5Ny4xNzc1NDg5NzU1*_ga_8JE65Q40S6*czE3NzkxMzM4NDIkbzUkZzEkdDE3NzkxMzUxOTckajE1JGwwJGgw",
      "https://images.pexels.com/photos/32315982/pexels-photo-32315982.jpeg?cs=srgb&dl=pexels-photos-hub-411139319-32315982.jpg&fm=jpg&_gl=1*o09i9*_ga*MTUzNzUzNzM5Ny4xNzc1NDg5NzU1*_ga_8JE65Q40S6*czE3NzkxMzM4NDIkbzUkZzEkdDE3NzkxMzUxNTMkajU5JGwwJGgw",
      "https://images.pexels.com/photos/8557657/pexels-photo-8557657.jpeg?cs=srgb&dl=pexels-rhea-jabagat-50266004-8557657.jpg&fm=jpg&_gl=1*1e3kqjw*_ga*MTUzNzUzNzM5Ny4xNzc1NDg5NzU1*_ga_8JE65Q40S6*czE3NzkxMzM4NDIkbzUkZzEkdDE3NzkxMzUxNTMkajU5JGwwJGgw"
    ]
  },
  {
    id: "6",
    title: "Leh Ladakh Bike Expedition",
    price: 25999,
    duration: "7N / 8D",
    dates: "Jul 1 \u2013 Jul 8, 2026",
    itinerary: [
      "Arrive Leh, acclimatization, Shanti Stupa visit.",
      "Leh sightseeing \u2013 Leh Palace, local monasteries.",
      "Ride to Nubra Valley via Khardung La.",
      "Nubra Valley \u2013 Diskit Monastery, double-hump camel ride.",
      "Ride to Pangong Lake, lakeside camping.",
      "Pangong to Leh via Chang La.",
      "Magnetic Hill, Confluence point, local market.",
      "Departure from Leh."
    ],
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1200&q=80",
    videoUrl: VID.bike,
    plannerName: "Vikram Singh",
    plannerAbout: "Motorcycle touring expert with 50+ Ladakh expeditions under his belt.",
    companyId: "ride-india",
    rating: 4.9,
    booked: 85,
    popular: true,
    location: "Leh, Ladakh",
    destination: "Ladakh",
    gallery: [
      "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80",
      "https://images.pexels.com/photos/9940766/pexels-photo-9940766.jpeg?cs=srgb&dl=pexels-cottonbro-9940766.jpg&fm=jpg&_gl=1*1efbdyt*_ga*MTUzNzUzNzM5Ny4xNzc1NDg5NzU1*_ga_8JE65Q40S6*czE3NzkxMzM4NDIkbzUkZzEkdDE3NzkxMzU1NDckajM0JGwwJGgw",
      "https://images.pexels.com/photos/28438644/pexels-photo-28438644.jpeg?cs=srgb&dl=pexels-spiritualsherpa-28438644.jpg&fm=jpg&_gl=1*1f9izvr*_ga*MTUzNzUzNzM5Ny4xNzc1NDg5NzU1*_ga_8JE65Q40S6*czE3NzkxMzM4NDIkbzUkZzEkdDE3NzkxMzU0NTMkajUzJGwwJGgw",
      "https://images.pexels.com/photos/33792541/pexels-photo-33792541.jpeg?cs=srgb&dl=pexels-ex-route-adventures-656223369-33792541.jpg&fm=jpg&_gl=1*1cck4td*_ga*MTUzNzUzNzM5Ny4xNzc1NDg5NzU1*_ga_8JE65Q40S6*czE3NzkxMzM4NDIkbzUkZzEkdDE3NzkxMzU2MDMkajUzJGwwJGgw",
      "https://images.pexels.com/photos/35328601/pexels-photo-35328601.jpeg?cs=srgb&dl=pexels-zikriyeah-35328601.jpg&fm=jpg&_gl=1*cxehbl*_ga*MTUzNzUzNzM5Ny4xNzc1NDg5NzU1*_ga_8JE65Q40S6*czE3NzkxMzM4NDIkbzUkZzEkdDE3NzkxMzU1MjIkajU5JGwwJGgw",
      "https://images.pexels.com/photos/13004767/pexels-photo-13004767.jpeg?cs=srgb&dl=pexels-kevin-kleber-64080845-13004767.jpg&fm=jpg&_gl=1*15rny3t*_ga*MTUzNzUzNzM5Ny4xNzc1NDg5NzU1*_ga_8JE65Q40S6*czE3NzkxMzM4NDIkbzUkZzEkdDE3NzkxMzU1NzkkajIkbDAkaDA."
    ]
  }
];
var destinations = [
  { name: "Himachal", emoji: "\u{1F3D4}\uFE0F", image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=600&q=80" },
  { name: "Goa", emoji: "\u{1F334}", image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=600&q=80" },
  { name: "Kerala", emoji: "\u{1F6F6}", image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600&q=80" },
  { name: "Rajasthan", emoji: "\u{1F3F0}", image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=600&q=80" },
  { name: "Andaman", emoji: "\u{1F3DD}\uFE0F", image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&q=80" },
  { name: "Ladakh", emoji: "\u{1F3CD}\uFE0F", image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&q=80" }
];

// src/lib/mcp/tools/search-trips.ts
var search_trips_default = defineTool({
  name: "search_trips",
  title: "Search trips",
  description: "Search the Trippinity trip catalog by destination, budget, duration and rating. Returns matching trips with id, title, price, duration, destination, rating and planner.",
  inputSchema: {
    query: z.string().optional().describe("Free-text query matched against trip title and location."),
    destination: z.string().optional().describe("Destination name filter, e.g. 'Goa', 'Kerala', 'Ladakh'."),
    maxPrice: z.number().int().positive().optional().describe("Max price in INR."),
    minPrice: z.number().int().positive().optional().describe("Min price in INR."),
    minRating: z.number().min(0).max(5).optional().describe("Minimum trip rating."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, destination, maxPrice, minPrice, minRating, limit }) => {
    const q = query?.trim().toLowerCase();
    const dest = destination?.trim().toLowerCase();
    const results = mockTrips.filter((t) => dest ? t.destination.toLowerCase().includes(dest) : true).filter((t) => maxPrice ? t.price <= maxPrice : true).filter((t) => minPrice ? t.price >= minPrice : true).filter((t) => minRating ? t.rating >= minRating : true).filter(
      (t) => q ? t.title.toLowerCase().includes(q) || t.location.toLowerCase().includes(q) : true
    ).slice(0, limit ?? 10).map((t) => ({
      id: t.id,
      title: t.title,
      price: t.price,
      duration: t.duration,
      destination: t.destination,
      location: t.location,
      rating: t.rating,
      booked: t.booked,
      planner: t.plannerName,
      companyId: t.companyId
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { count: results.length, results }
    };
  }
});

// src/lib/mcp/tools/get-trip-details.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_trip_details_default = defineTool2({
  name: "get_trip_details",
  title: "Get trip details",
  description: "Fetch the full details of a Trippinity trip by id: itinerary, dates, gallery, planner and company info.",
  inputSchema: {
    id: z2.string().min(1).describe("The trip id, e.g. '1'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const trip = mockTrips.find((t) => t.id === id);
    if (!trip) {
      return {
        content: [{ type: "text", text: `No trip found with id "${id}".` }],
        isError: true
      };
    }
    const company = companies[trip.companyId] ?? null;
    const detail = { ...trip, company };
    return {
      content: [{ type: "text", text: JSON.stringify(detail, null, 2) }],
      structuredContent: detail
    };
  }
});

// src/lib/mcp/tools/list-destinations.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_destinations_default = defineTool3({
  name: "list_destinations",
  title: "List destinations",
  description: "List all destinations Trippinity covers, with the number of trips available in each.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const results = destinations.map((d) => ({
      name: d.name,
      emoji: d.emoji,
      tripCount: mockTrips.filter((t) => t.destination === d.name).length
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { count: results.length, destinations: results }
    };
  }
});

// src/lib/mcp/tools/list-planners.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_planners_default = defineTool4({
  name: "list_planners",
  title: "List verified planners",
  description: "List all verified Trippinity travel planners (companies) with their ratings and trip counts.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const results = Object.values(companies).map((c) => ({
      id: c.id,
      name: c.name,
      verified: c.verified,
      rating: c.rating,
      trips: c.trips,
      about: c.about,
      liveTripCount: mockTrips.filter((t) => t.companyId === c.id).length
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { count: results.length, planners: results }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kqgcnnsmcehsykfaccpf";
var mcp_default = defineMcp({
  name: "trippinity-mcp",
  title: "Trippinity",
  version: "0.1.0",
  instructions: "Tools for Trippinity \u2014 a curated travel marketplace. Use `search_trips` to find trips by destination/budget/rating, `get_trip_details` to fetch full itinerary + planner info, `list_destinations` to see what's covered, and `list_planners` to browse verified operators.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_trips_default, get_trip_details_default, list_destinations_default, list_planners_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
