// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/search-trips.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
import { mockTrips } from "npm:@/data/mockTrips";
var search_trips_default = defineTool({
  name: "search_trips",
  title: "Search trips",
  description: "Search the Trippinity trip catalog by destination, budget, duration and rating. Returns matching trips with id, title, price, duration, destination, rating and planner.",
  inputSchema: {
    query: z.string().optional().describe("Free-text query matched against trip title and location."),
    destination: z.string().optional().describe("Destination name filter, e.g. 'Goa', 'Kerala', 'Ladakh'."),
    maxPrice: z.number().int().positive().optional().describe("Max price in INR."),
    minPrice: z.number().int().positive().optional().describe("Min price in INR."),
    minRating: z.number().min(0).max(5).optional().describe("Minimum trip rating."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, destination, maxPrice, minPrice, minRating, limit }) => {
    const q = query?.trim().toLowerCase();
    const dest = destination?.trim().toLowerCase();
    const results = mockTrips.filter((t) => dest ? t.destination.toLowerCase().includes(dest) : true).filter((t) => maxPrice ? t.price <= maxPrice : true).filter((t) => minPrice ? t.price >= minPrice : true).filter((t) => minRating ? t.rating >= minRating : true).filter(
      (t) => q ? t.title.toLowerCase().includes(q) || t.location.toLowerCase().includes(q) : true
    ).slice(0, limit ?? 10).map((t) => ({
      id: t.id,
      title: t.title,
      price: t.price,
      duration: t.duration,
      destination: t.destination,
      location: t.location,
      rating: t.rating,
      booked: t.booked,
      planner: t.plannerName,
      companyId: t.companyId
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { count: results.length, results }
    };
  }
});

// src/lib/mcp/tools/get-trip-details.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { mockTrips as mockTrips2, companies } from "npm:@/data/mockTrips";
var get_trip_details_default = defineTool2({
  name: "get_trip_details",
  title: "Get trip details",
  description: "Fetch the full details of a Trippinity trip by id: itinerary, dates, gallery, planner and company info.",
  inputSchema: {
    id: z2.string().min(1).describe("The trip id, e.g. '1'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const trip = mockTrips2.find((t) => t.id === id);
    if (!trip) {
      return {
        content: [{ type: "text", text: `No trip found with id "${id}".` }],
        isError: true
      };
    }
    const company = companies[trip.companyId] ?? null;
    const detail = { ...trip, company };
    return {
      content: [{ type: "text", text: JSON.stringify(detail, null, 2) }],
      structuredContent: detail
    };
  }
});

// src/lib/mcp/tools/list-destinations.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { destinations, mockTrips as mockTrips3 } from "npm:@/data/mockTrips";
var list_destinations_default = defineTool3({
  name: "list_destinations",
  title: "List destinations",
  description: "List all destinations Trippinity covers, with the number of trips available in each.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const results = destinations.map((d) => ({
      name: d.name,
      emoji: d.emoji,
      tripCount: mockTrips3.filter((t) => t.destination === d.name).length
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { count: results.length, destinations: results }
    };
  }
});

// src/lib/mcp/tools/list-planners.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { companies as companies2, mockTrips as mockTrips4 } from "npm:@/data/mockTrips";
var list_planners_default = defineTool4({
  name: "list_planners",
  title: "List verified planners",
  description: "List all verified Trippinity travel planners (companies) with their ratings and trip counts.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const results = Object.values(companies2).map((c) => ({
      id: c.id,
      name: c.name,
      verified: c.verified,
      rating: c.rating,
      trips: c.trips,
      about: c.about,
      liveTripCount: mockTrips4.filter((t) => t.companyId === c.id).length
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { count: results.length, planners: results }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kqgcnnsmcehsykfaccpf";
var mcp_default = defineMcp({
  name: "trippinity-mcp",
  title: "Trippinity",
  version: "0.1.0",
  instructions: "Tools for Trippinity \u2014 a curated travel marketplace. Use `search_trips` to find trips by destination/budget/rating, `get_trip_details` to fetch full itinerary + planner info, `list_destinations` to see what's covered, and `list_planners` to browse verified operators.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_trips_default, get_trip_details_default, list_destinations_default, list_planners_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
